### ISSUE TITLE
Is it possible to use this repo without hardware, only with Moveit?

### ISSUE THREAD

**Issue by Shreeyak** [NiryoRobotics/niryo_one_ros#8]
Hi, I've been using your repo as a reference while building my own application. Excellent docs, thank you so much. They've helped me out a ton. I'm sure this will make Niryo a nice learning platform.

So I've trying to figure out how to connect moveit to ros_control. I notice in your code that you have a "fake" communications base. i infer that this is used to connect and test moveit with ros_control in the absence of real hardware. 

Could you tell me how to run and test the code base using just moveit, with no hardware at hand?

**Comment by renarded** [comment]
Hi,

Thanks for your support. 

Yes, you can already use this repo without hardware !

To get the same Moveit! features you need to launch 

`roslaunch niryo_one_bringup desktop_rviz_simulation.launch`

You can check this launch file, it will launch everything but not the hardware driver and not the Raspberry Pi hardware functionalities. It will also launch the controller (using ros_control) with a "fake communication", which means that the [hardware_interface](https://github.com/ros-controls/ros_control/wiki/hardware_interface) will just echo the command on the current state, instead of passing the command to the motors, and receiving the state from sensors.
